source 'https://github.com/CocoaPods/Specs.git'        #官方仓库地址
source 'https://git.coding.net/Eadkennychan/zwSpecs.git'

platform :ios, '8.0'

target 'CodeScannerDemo' do
  pod 'Masonry'
  pod 'CodeScanner', :path=>'..'
end
